"""Initial migration

Revision ID: 22b661a44476
Revises: 
Create Date: 2026-08-29 23:08:04.196485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22b661a44476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('SALES_MANAGER', 'SALES_REP')", name='check_user_role'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_owner_id'), ['owner_id'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('expected_close_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('previous_stage', sa.String(length=20), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('alert_dismissed_for_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("stage IN ('NEW','QUALIFIED','PROPOSAL','NEGOTIATION','WON','LOST')", name='check_deal_stage'),
    sa.CheckConstraint('value >= 0', name='check_deal_value_positive'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_stage'), ['stage'], unique=False)

    op.create_table('deal_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deal_id', 'user_id', name='uq_deal_collaborator')
    )
    op.create_table('deal_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("event_type IN ('DEAL_CREATED','STAGE_CHANGED','STAGE_BACKWARD','DEAL_REOPENED','DEAL_CLOSED','OWNER_CHANGED','COLLABORATOR_ADDED','COLLABORATOR_REMOVED','NOTE_ADDED')", name='check_event_type'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deal_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_history_deal_id'), ['deal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deal_history_deal_id'))
        batch_op.drop_index(batch_op.f('ix_deal_history_created_at'))

    op.drop_table('deal_history')
    op.drop_table('deal_collaborators')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_stage'))
        batch_op.drop_index(batch_op.f('ix_deals_owner_id'))
        batch_op.drop_index(batch_op.f('ix_deals_company_id'))
        batch_op.drop_index(batch_op.f('ix_deals_closed_at'))

    op.drop_table('deals')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_owner_id'))
        batch_op.drop_index(batch_op.f('ix_companies_archived_at'))

    op.drop_table('companies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
