"""add added_by to deal_collaborators

Revision ID: a942316df9ee
Revises: 22b661a44476
Create Date: 2026-08-30 14:28:09.467159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a942316df9ee'
down_revision = '22b661a44476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_collaborators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('added_by', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_deal_collaborators_deal_id'), ['deal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deal_collaborators_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_deal_collaborators_added_by', 'users', ['added_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deal_collaborators', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deal_collaborators_added_by', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_deal_collaborators_user_id'))
        batch_op.drop_index(batch_op.f('ix_deal_collaborators_deal_id'))
        batch_op.drop_column('added_by')

    # ### end Alembic commands ###
